# Generated by Django 3.2.5 on 2021-07-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_fieldname_registry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
