# Generated by Django 3.2.5 on 2021-07-12 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210712_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 20, 31, 31, 356239)),
        ),
        migrations.AlterField(
            model_name='registry',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
