# Generated by Django 2.2.24 on 2021-07-14 04:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210714_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='default_field',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 10, 22, 0, 677100)),
        ),
        migrations.AlterField(
            model_name='registry',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
