# Generated by Django 2.2.24 on 2021-07-14 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210714_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 10, 25, 37, 42912)),
        ),
        migrations.AlterField(
            model_name='registry',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
