# Generated by Django 2.2.24 on 2021-07-14 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210714_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registry',
            old_name='key_field',
            new_name='default_field',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='password',
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 18, 36, 58, 240274)),
        ),
    ]
