# Generated by Django 2.2.24 on 2021-07-14 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210714_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registry',
            old_name='passsword',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 18, 39, 52, 351511)),
        ),
    ]
