# Generated by Django 2.2.24 on 2021-07-14 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210714_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registry',
            name='key',
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 14, 19, 45, 45, 128851)),
        ),
    ]
