# Generated by Django 2.2.24 on 2021-07-15 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210714_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registry',
            old_name='is_staff',
            new_name='pending',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 15, 17, 56, 53, 613695)),
        ),
    ]
