# Generated by Django 2.2.24 on 2021-07-17 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210717_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 16, 40, 37, 218169)),
        ),
        migrations.AlterField(
            model_name='save_mail',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='save_mail',
            name='message',
            field=models.TextField(),
        ),
    ]
