# Generated by Django 2.2.24 on 2021-07-17 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210717_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save_mail',
            old_name='_from',
            new_name='to',
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 16, 57, 28, 822629)),
        ),
    ]
