# Generated by Django 2.2.24 on 2021-07-17 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210717_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_mail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 18, 52, 44, 107203)),
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 18, 52, 44, 107203)),
        ),
        migrations.AlterField(
            model_name='registry',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
