# Generated by Django 2.2.24 on 2021-07-18 17:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210717_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 22, 55, 58, 946256)),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to=None)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Save_Mail')),
            ],
        ),
    ]
