# Generated by Django 2.2.24 on 2021-07-18 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210718_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save_mail',
            name='file',
        ),
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.Save_Mail'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='files',
            field=models.FileField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 23, 13, 6, 388333)),
        ),
    ]
