# Generated by Django 2.2.24 on 2021-07-18 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210719_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='email',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 0, 46, 52, 40710)),
        ),
    ]
