# Generated by Django 2.2.24 on 2021-07-18 20:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210719_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='files',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Save_Mail'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 1, 42, 8, 165699)),
        ),
    ]
