# Generated by Django 2.2.24 on 2021-07-18 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210719_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='name',
        ),
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.EmailField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 1, 43, 28, 643021)),
        ),
    ]
