# Generated by Django 2.2.24 on 2021-07-18 20:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20210719_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 1, 43, 41, 930046)),
        ),
    ]
