# Generated by Django 2.2.24 on 2021-07-20 03:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20210720_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 8, 34, 58, 792123)),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Save_Mail'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 8, 34, 58, 792123)),
        ),
        migrations.AlterField(
            model_name='save_mail',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
