# Generated by Django 2.2.24 on 2021-07-20 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20210720_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 9, 1, 19, 733001)),
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 9, 1, 19, 733001)),
        ),
        migrations.AlterField(
            model_name='save_mail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 9, 1, 19, 733001)),
        ),
        migrations.AlterField(
            model_name='save_mail',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
