# Generated by Django 2.2.24 on 2021-07-20 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20210720_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 9, 4, 1, 508005)),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 9, 4, 1, 508005)),
        ),
        migrations.AlterField(
            model_name='save_mail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 9, 4, 1, 508005)),
        ),
        migrations.AlterField(
            model_name='save_mail',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
