# Generated by Django 2.2.24 on 2021-07-20 03:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20210720_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 9, 26, 55, 41235)),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Save_Mail'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 9, 26, 55, 25610)),
        ),
        migrations.AlterField(
            model_name='save_mail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 9, 26, 55, 41235)),
        ),
        migrations.AlterField(
            model_name='save_mail',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
