# Generated by Django 2.2.24 on 2021-07-30 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20210720_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='registry',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 18, 53, 18, 584369)),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attach', to='accounts.Save_Mail'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 18, 53, 18, 584369)),
        ),
        migrations.AlterField(
            model_name='save_mail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 30, 18, 53, 18, 584369)),
        ),
    ]
